name: CI
run-name: ${{ github.actor }}
on: [push]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: |
                  echo "Running Installing Dependencies...."
                  pnpm install
            - name: Build
              run: |
                  echo "Running Build...."
                  pnpm run build
